extern struct session *all_command(char *arg, struct session *ses);
extern struct session *session_command(char *arg, struct session *ses);
extern struct session *sslsession_command(char *arg, struct session *ses);
extern struct session *read_command(char *arg, struct session *ses);
extern struct session *run_command(char *arg, struct session *ses);
extern struct session *zap_command(char *arg, struct session *ses);
extern void            verbatim_command(char *arg, struct session *ses);
extern void            action_command(char *arg, struct session *ses);
extern void            alias_command(char *arg, struct session *ses);
extern void            antisubstitute_command(char *arg, struct session *ses);
extern void            bell_command(char *arg, struct session *ses);
extern void            blank_command(char *arg, struct session *ses);
extern void            char_command(char *arg, struct session *ses);
extern void            condump_command(char *arg, struct session *ses);
extern void            bind_command(char *arg, struct session *ses);
extern void            keypad_command(char *arg, struct session *ses);
extern void            ctime_command(char *arg, struct session *ses);
extern void            cr_command(char *arg, struct session *ses);
extern void            delay_command(char *arg, struct session *ses);
extern void            event_command(char *arg, struct session *ses);
extern void            deleteitems_command(char *arg, struct session *ses);
extern void            deathlog_command(char *arg, struct session *ses);
extern void            echo_command(char *arg, struct session *ses);
extern void            explode_command(char *arg, struct session *ses);
extern struct session *foreach_command(char *arg, struct session *ses);
extern struct session *forall_command(char *arg, struct session *ses);
extern void            firstupper_command(char *arg, struct session *ses);
extern void            help_command(char *arg, struct session *ses);
extern void            highlight_command(char *arg, struct session *ses);
extern void            history_command(char *arg, struct session *ses);
extern struct session *if_command(char *arg, struct session *ses);
extern void            else_command(char *arg, struct session *ses);
extern void            elif_command(char *arg, struct session *ses);
extern void            finditem_command(char *arg, struct session *ses);
extern void            getitem_command(char *arg, struct session *ses);
extern void            goto_command(char *arg, struct session *ses);
extern void            ignore_command(char *arg, struct session *ses);
extern void            implode_command(char *arg, struct session *ses);
extern void            info_command(char *arg, struct session *ses);
extern void            isatom_command(char *arg, struct session *ses);
extern void            killall_command(char *arg, struct session *ses);
extern void            listlength_command(char *arg, struct session *ses);
extern void            log_command(char *arg, struct session *ses);
extern void            loop_command(char *arg, struct session *ses);
extern void            nope_command(char *arg, struct session *ses);
extern void            map_command(char *arg, struct session *ses);
extern void            margins_command(char *arg, struct session *ses);
extern void            math_command(char *arg, struct session *ses);
extern void            match_command(char *arg, struct session *ses);
extern void            mark_command(char *arg, struct session *ses);
extern void            messages_command(char *arg, struct session *ses);
extern void            mudcolors_command(char *arg, struct session *ses);
extern void            news_command(char *arg, struct session *ses);
extern void            path_command(char *arg, struct session *ses);
extern void            pathdir_command(char *arg, struct session *ses);
extern void            presub_command(char *arg, struct session *ses);
extern void            prepad_command(char *arg, struct session *ses);
extern void            promptaction_command(char *arg, struct session *ses);
extern void            postpad_command(char *arg, struct session *ses);
extern void            random_command(char *arg, struct session *ses);
extern void            remark_command(char *arg, struct session *ses);
extern void            removeevent_command(char *arg, struct session *ses);
extern void            undelay_command(char *arg, struct session *ses);
extern void            unevent_command(char *arg, struct session *ses);
extern void            unpathdir_command(char *arg, struct session *ses);
extern void            return_command(char *arg, struct session *ses);
extern void            reverse_command(char *arg, struct session *ses);
extern void            route_command(char *arg, struct session *ses);
extern void            savepath_command(char *arg, struct session *ses);
extern void            showme_command(char *arg, struct session *ses);
extern void            snoop_command(char *arg, struct session *ses);
extern void            speedwalk_command(char *arg, struct session *ses);
extern void            splitlist_command(char *arg, struct session *ses);
extern void            suspend_command(char *arg, struct session *ses);
extern void            shell_command(char *arg, struct session *ses);
extern void            status_command(char *arg, struct session *ses);
extern void            textin_command(char *arg, struct session *ses);
extern void            time_command(char *arg, struct session *ses);
extern void            sortlist_command(char *arg, struct session *ses);
extern void            substitute_command(char *arg, struct session *ses);
extern void            gag_command(char *arg, struct session *ses);
extern void            substring_command(char *arg, struct session *ses);
extern void            strlen_command(char *arg, struct session *ses);
extern void            system_command(char *arg, struct session *ses);
extern void            tick_command(char *arg, struct session *ses);
extern void            tickoff_command(char *arg, struct session *ses);
extern void            tickon_command(char *arg, struct session *ses);
extern void            ticksize_command(char *arg, struct session *ses);
extern void            tolower_command(char *arg, struct session *ses);
extern void            togglesubs_command(char *arg, struct session *ses);
extern void            toupper_command(char *arg, struct session *ses);
extern void            unaction_command(char *arg, struct session *ses);
extern void            unalias_command(char *arg, struct session *ses);
extern void            unantisubstitute_command(char *arg, struct session *ses);
extern void            unbind_command(char *arg, struct session *ses);
extern void            unhighlight_command(char *arg, struct session *ses);
extern void            unsubstitute_command(char *arg, struct session *ses);
extern void            ungag_command(char *arg, struct session *ses);
extern void            unpromptaction_command(char *arg, struct session *ses);
extern void            unmap_command(char *arg, struct session *ses);
extern void            unroute_command(char *arg, struct session *ses);
extern void            variable_command(char *arg, struct session *ses);
extern void            version_command(char *arg, struct session *ses);
extern void            unvariable_command(char *arg, struct session *ses);
extern void            write_command(char *arg, struct session *ses);
extern void            writesession_command(char *arg, struct session *ses);
extern void            dosubstitutes_command(char *arg, struct session *ses);
extern void            dohighlights_command(char *arg, struct session *ses);
extern void            decolorize_command(char *arg, struct session *ses);
extern void            atoi_command(char *arg, struct session *ses);
extern struct session *strcmp_command(char *arg, struct session *ses);
extern void            verbose_command(char *arg, struct session *ses);
extern void            dogoto_command(char *arg, struct session *ses);
extern void            changeto_command(char *arg, struct session *ses);
extern void            send_command(char *arg, struct session *ses);
extern void            timecommands_command(char *arg, struct session *ses);
extern void            debuglog_command(char *arg, struct session *ses);
extern void            logtype_command(char *arg, struct session *ses);
#ifdef HAVE_REGCOMP
extern void            grep_command(char *arg, struct session *ses);
#endif
extern void            retain_command(char *arg, struct session *ses);
extern struct session *ifexists_command(char *arg, struct session *ses);
extern struct session *ifstrequal_command(char *arg, struct session *ses);
#ifdef TERM_DEBUG
extern void            termdebug_command(char *arg, struct session *ses);
#endif
extern void            pretick_command(char *arg, struct session *ses);
extern void            show_pretick_command(char *arg, struct session *ses);
extern void            collate_command(char *arg, struct session *ses);
extern void            expand_command(char *arg, struct session *ses);
extern void            hooks_command(char *arg, struct session *ses);
extern void            unhook_command(char *arg, struct session *ses);
extern void            logcomment_command(char *arg, struct session *ses);
extern void            gagthis_command(char *arg, struct session *ses);
#ifdef PROFILING
extern void            profile_command(char *arg, struct session *ses);
#endif
extern void            charset_command(char *arg, struct session *ses);
extern void            logcharset_command(char *arg, struct session *ses);
extern void            doactions_command(char *arg, struct session *ses);
extern void            dopromptactions_command(char *arg, struct session *ses);
extern void            chr_command(char *arg, struct session *ses);
extern void            ord_command(char *arg, struct session *ses);
extern void            hexord_command(char *arg, struct session *ses);
extern void            localtime_command(char *arg, struct session *ses);
extern void            gmtime_command(char *arg, struct session *ses);
extern void            ctoi_command(char *arg, struct session *ses);
extern void            loginputformat_command(char *arg, struct session *ses);
extern void            initvariable_command(char *arg, struct session *ses);
